### ISSUE TITLE
Calculus II Mark some sections optional, remove L'Hospital's Rule

### ISSUE THREAD

**Issue by tomgonzalez** [DaltonStateCollege/calculus-text#12]
Mark the following sections as optional:  5.6 Hyperbolic Functions, 6.6 Fluid Forces, 8.1 Conic Sections.

Remove L'Hospital's Rule due to being in Cal I. 

Rename Section 5.8 to Improper Integrals

**Comment by mjjoseph** [comment]
Done (those section numbers are off and L'Hop was already moved to Chapter 4).
