### ISSUE TITLE
Section 6.2 Trigonometric Integrals  Missing Case

### ISSUE THREAD

**Issue by tomgonzalez** [DaltonStateCollege/calculus-text#26]
None of the cases in the Integrals Involving Powers of Tangent and Secant apply to integrating odd powers of tangent with no secants.

**Comment by mjjoseph** [comment]
Yeah, I noticed that last semester too.  Anyhow, it was an easy fix because the same technique that works for even powers also works for odd.  So I replaced "m even" with "m\geq 2".  I also added exercises, namely one of each type (indefinite integral, definite integral, initial value problem).
