### ISSUE TITLE
Antiderivatives of tan(x) and csc(x)

### ISSUE THREAD

**Issue by tomgonzalez** [DaltonStateCollege/calculus-text#29]
Change antiderivatives of tangent and cosecant functions to

$\int \; tan(x) \; dx = \ln| sec(x) | + C$

$\int \; csc(x) \; dx = \ln| csc(x) - cot(x) | + C$

**Comment by mjjoseph** [comment]
I disagree with this change.  They're equivalent by log properties and trig identities.  The way they're stated in the text is most natural for remembering derivatives and antiderivativess of trig functions.  If you know the derivative or antiderivative of sin(x), tan(x), sec(x), you can remember the "cofunctions" by changing between co and not-co, and changing the sign in front.

If you remember the antiderivative of sec(x) is ln | sec(x)+tan(x) | + C, you get the one for csc(x) by changing sec(x) to csc(x) and tan(x) to cot(x) and putting the minus sign in front.
So $\int ; csc(x) ; dx = - \ln| csc(x) + cot(x) | + C$.

**Comment by tomgonzalez** [comment]
Left unchanged
