### ISSUE TITLE
Section 4.1  Related Rate Answers

### ISSUE THREAD

**Issue by tomgonzalez** [DaltonStateCollege/calculus-text#40]
Attach signs to answers to be less confusing?

**Comment by mjjoseph** [comment]
I disagree.  With the way the problems are worded, the positive answers are correct.  You don't say a boat is approaching a dock at -301 ft/min.  You say 301 ft/min, and "approaching the dock" refers to the direction.  I think students need to learn to understand this difference, and it goes both ways.  If the problem reads "reeled in at 30 ft/min", they need to recognize that dl / dt = -30 ft/min; the problem won't have the sign there.  If students express confusion, and it leads to a discussion for why the sign isn't there, then that's part of learning.

**Comment by tomgonzalez** [comment]
Sounds good!
